export type UserData = {
  createdAt: Date;
  displayName: string;
  email: string;
  isAnonymous: boolean;
};

export type AdditionalInformation = {
  displayName?: string;
};

export enum USER_ACTION_TYPES {
  SIGN_IN_AND_SET_USER = "SIGN_IN_AND_SET_USER",
  TOGGLE_SORTING_ASCENDING = "TOGGLE_SORTING_ASCENDING",
  SET_SORTING_BY_PRICE = "SET_SORTING_BY_PRICE",
  SET_SORTING_APLPHABETIC = "SET_SORTING_APLPHABETIC",
  SET_SORTING_INPUT = "SET_SORTING_INPUT",
  SET_ORDER_HISTORY = "SET_ORDER_HISTORY",

  SIGN_OUT_START = "SIGN_OUT_START",
  SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED = "SIGN_OUT_FAILED",

  SIGN_UP_START = "SIGN_UP_START",
  SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED = "SIGN_UP_FAILED",

  ANYNOMOUS_SIGN_IN_START = "ANYNOMOUS_SIGN_IN_START",
  GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START = "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED = "SIGN_IN_FAILED"
}
