export enum USER_ACTION_TYPES {
  SET_USER = "SET_THEME",
  TOGGLE_USER_MENU = "TOGGLE_USER_MENU",
  TOGGLE_SORTING_ASCENDING = "TOGGLE_SORTING_ASCENDING",
  SET_SORTING_BY_PRICE = "SET_SORTING_BY_PRICE",
  SET_SORTING_APLPHABETIC = "SET_SORTING_APLPHABETIC"
}
