export enum GENERAL_PROPS_ACTION_TYPES {
  SET_THEME = "SET_THEME",
  SET_PATH = "SET_PATH",
  TOGGLE_USER_MENU = "TOGGLE_USER_MENU",

  SET_VIEW_LIMITER = "SET_VIEW_LIMITER"
}

export type PathType = string;
